[phases.setup]
nixPkgs = ["nodejs", "nodePackages.yarn", "chromium"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build", "yarn prisma generate"]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=128" 