[phases.setup]
nixPkgs = ["nodejs", "nodePackages.npm", "chromium"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm start" 